### ISSUE TITLE
Cooldown swipe Frame strata issue

### ISSUE THREAD

**Issue by Nillx** [a-vasilev/classic-loca#1]
Cooldown swipe animation seems to appear over the map texture while the rest is hidden under it.

![2323](https://user-images.githubusercontent.com/34476875/119240638-a898c600-bb59-11eb-9372-6ecad5808b76.JPG)

**Comment by a-vasilev** [comment]
Thank you for the issue. I couldn't exactly reproduce it with the map for some reason, but it was definitely happening with other default UI elements.

**Comment by Nillx** [comment]
Благодаря за бързия фикс :) (За карта ползвам Leatrix Maps и за това най-вероятно не се е появявало като си го тествал)
